---
- name: Create .local directory
  file: path=/home/rtorrent/.local state=directory owner=rtorrent group=rtorrent mode=0750

- name: Install build dependencies for pyenv
  apt:
    state: latest
    name:
      - build-essential
      - curl
      - llvm
      - make
      - wget
      - xz-utils
      - zlib1g-dev
      - libbz2-dev
      - libssl-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncurses5-dev
      - libncursesw5-dev

- name: Probe pyenv checkout
  stat: path=/home/rtorrent/.local/pyenv/plugins/pyenv-installer/.gitignore
  register: pyenv_flagfile

- name: git clone pyenv project
  git: repo=https://github.com/yyuu/pyenv.git dest=/home/rtorrent/.local/pyenv
  when: not pyenv_flagfile.stat.exists

- name: Create plugins directory
  file: path=/home/rtorrent/.local/pyenv/plugins state=directory owner=rtorrent group=rtorrent mode=0750

- name: git clone pyenv plugins
  git:
    repo: https://github.com/yyuu/{{ item }}.git
    dest: /home/rtorrent/.local/pyenv/plugins/{{ item }}
  when: not pyenv_flagfile.stat.exists
  with_items:
    - pyenv-doctor
    - pyenv-update
    - pyenv-virtualenv
    - pyenv-which-ext
    - pyenv-installer

- name: Fix pyenv ownership
  file: path=/home/rtorrent/.local/pyenv state=directory recurse=true owner=rtorrent group=rtorrent
  when: not pyenv_flagfile.stat.exists

- name: Install pyenv activation
  copy: src=pyenv.sh dest=/home/rtorrent/.local/profile.d/pyenv.sh owner=rtorrent group=rtorrent mode=0640

- name: Probe Python installation
  stat: path=/home/rtorrent/.local/pyenv/version
  register: pyenv_py_flagfile

- name: Install Python
  shell: su -c '. .bash_aliases; TMPDIR=$PWD/tmp pyenv install {{ pyenv_python_version }}' rtorrent
  args:
    executable: /bin/bash
    chdir: /home/rtorrent
    creates: "/home/rtorrent/.local/pyenv/versions/{{ pyenv_python_version }}/bin/python"
  when: not pyenv_py_flagfile.stat.exists

- name: Update pip tooling
  shell: su -c '.local/pyenv/versions/{{ pyenv_python_version }}/bin/python -m pip install -U pip setuptools wheel' rtorrent
  args:
    executable: /bin/bash
    chdir: /home/rtorrent
  when: not pyenv_py_flagfile.stat.exists

- name: Install virtualenv
  shell: su -c '.local/pyenv/versions/{{ pyenv_python_version }}/bin/python -m pip install -U virtualenv' rtorrent
  args:
    executable: /bin/bash
    chdir: /home/rtorrent
    creates: "/home/rtorrent/.local/pyenv/versions/{{ pyenv_python_version }}/bin/virtualenv"
  when: "not pyenv_py_flagfile.stat.exists and pyenv_python_version < '3'"

- name: Define global pyenv version
  copy:
    content: "{{ pyenv_python_version }}"
    dest: /home/rtorrent/.local/pyenv/version
    owner: rtorrent
    group: rtorrent
    mode: 0640
    force: no
